//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace itslearningTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("itslearningTest.ExceptionRes", typeof(ExceptionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername oder das Passwort sind falsch. Bitte überprüfen Sie Ihre Eingaben und versuchen Sie es erneut..
        /// </summary>
        internal static string ATUnauthorizedAccessExcpetionMsg {
            get {
                return ResourceManager.GetString("ATUnauthorizedAccessExcpetionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Anfrage konnte nicht bearbeitet werden, wegen: .
        /// </summary>
        internal static string DefaultExceptionMsg {
            get {
                return ResourceManager.GetString("DefaultExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut. Weitere Informationen:.
        /// </summary>
        internal static string InvalidOperationExceptionMsg {
            get {
                return ResourceManager.GetString("InvalidOperationExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Benutzername und das Passwort dürfen nicht leer sein. Bitte überprüfen Sie Ihre Eingabe und versuchen Sie es erneut..
        /// </summary>
        internal static string ItslArgumentNullExceptionMsg {
            get {
                return ResourceManager.GetString("ItslArgumentNullExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Auswertung der JSON-Daten ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut. Weitere Informationen: .
        /// </summary>
        internal static string JsonExceptionMsg {
            get {
                return ResourceManager.GetString("JsonExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainExceptionDialogContBtnPrimitive {
            get {
                return ResourceManager.GetString("MainExceptionDialogContBtnPrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string MainExceptionDialogTitlePrimitive {
            get {
                return ResourceManager.GetString("MainExceptionDialogTitlePrimitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainOKButton {
            get {
                return ResourceManager.GetString("MainOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler – Sicherer Speicher.
        /// </summary>
        internal static string MainSecureStorageReadErrorHeader {
            get {
                return ResourceManager.GetString("MainSecureStorageReadErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Lesen der Benutzerdaten ist ein Fehler aufgetreten. Bitte melden Sie sich erneut an. Weitere Informationen: .
        /// </summary>
        internal static string MainSecureStorageReadErrorMsg {
            get {
                return ResourceManager.GetString("MainSecureStorageReadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string MainSeucreStorageReadErrorBtn {
            get {
                return ResourceManager.GetString("MainSeucreStorageReadErrorBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Senden der E-Mail zum Zurücksetzen des Passworts ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut. .
        /// </summary>
        internal static string PasswordResetEmailErrorMsg {
            get {
                return ResourceManager.GetString("PasswordResetEmailErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wenn Sie Ihre E-Mail-Adresse in itslearning hinterlegt haben, erhalten Sie in einigen Minuten eine E-Mail mit Anweisungen zum zurücksetzen des Passworts. Bitte sehen Sie auch im Spam-Ordner nach. Falls Sie keine E-Mail erhalten haben, überprüfen Sie bitte, ob Sie die richtige E-Mail-Adresse eingeben haben oder wenden Sie sich an Ihren Administrator..
        /// </summary>
        internal static string PasswordResetEmailSuccessMsg {
            get {
                return ResourceManager.GetString("PasswordResetEmailSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie wurden abgemeldet, weil der Zugriffsschlüssel nicht gültig, abgelaufen oder leer ist. Melden Sie sich erneut an, indem Sie auf „OK“ klicken. Weitere Informationen: .
        /// </summary>
        internal static string UnauthorizedAccessExceptionAdvancedMsg {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionAdvancedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffsschlüssel ist nicht gültig, abgelaufen oder leer..
        /// </summary>
        internal static string UnauthorizedAccessExceptionMsg {
            get {
                return ResourceManager.GetString("UnauthorizedAccessExceptionMsg", resourceCulture);
            }
        }
    }
}
