//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schülerfirma_Admin_Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PredefinedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PredefinedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schülerfirma_Admin_Dashboard.PredefinedMessages", typeof(PredefinedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ____Keine____ {
            get {
                return ResourceManager.GetString("--- Keine ---", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {name}, 
        ///für die zwischen dem {startDate} und {endDate} erbrachten Leistungen haben wir leider noch keinen Zalungseingang von Ihnen feststellen können. Sicher haben Sie dies übersehen. Ich bitte Sie deshalb, die Zahlung möglichst bald nachzuholen. 
        ///Vielen Dank im Voraus. 
        ///Bei Fragen sind wir gerne für Sie da. 
        ///Mit freundlichen Grüßen
        ///Schülerfirma der CSH.
        /// </summary>
        internal static string Zahlungserinnerung_I {
            get {
                return ResourceManager.GetString("Zahlungserinnerung I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {name}, 
        ///bis zum heutigen Tag wurde die Rechnung Nr. {bookingnr} für den Zeitraum vom {startDate} bis {endDate} und einem Zahlungsbetrag in Höhe von {amountDue} € nicht beglichen. Die Zahlung war bereits am {paymentDue} fällig. 
        ///Wir möchten Sie daher bitten, dies innerhalb der nächsten 7 Tage nachzuholen. 
        ///Falls Sie Fragen haben oder wir Ihnen in einer anderen Sache weiterhelfen dürfen, können Sie gerne Kontakt zu uns aufnehmen. 
        ///Sollte sich Ihre mittlerweile erfolgte Zahlung und diese Erinnerung  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zahlungserinnerung_II {
            get {
                return ResourceManager.GetString("Zahlungserinnerung II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo {name}, 
        ///dies ist die dritte und letzte Zahlungserinnerung, die Sie von uns erhalten werden. 
        ///Sie schulden uns {amountDue} €.
        ///Zahlen Sie endlich Ihre Rechnung, sonst kommen wir zu Ihnen! 
        ///Mit freundlichen Grüßen
        ///Schülerfirma der CSH.
        /// </summary>
        internal static string Zahlungserinnerung_III {
            get {
                return ResourceManager.GetString("Zahlungserinnerung III", resourceCulture);
            }
        }
    }
}
